# Generated by Django 4.1.1 on 2022-11-21 22:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='base64',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, storage=django.core.files.storage.FileSystemStorage(location='/media/Sheets'), upload_to='', verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
