# Generated by Django 4.1.1 on 2022-11-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_file_base64_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.IntegerField(choices=[(1, 'Atleta'), (2, 'Campeonato')], default=1, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
