# Generated by Django 4.1.1 on 2022-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_athlete_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_code',
            field=models.TextField(max_length=255, verbose_name='Id do Atleta'),
        ),
    ]
