# Generated by Django 4.1.1 on 2022-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_athlete_athlete_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='importation_file_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Idade de Corte'),
        ),
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.TextField(max_length=255, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Nome da Categoria'),
        ),
    ]
