# Generated by Django 4.1.1 on 2022-12-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_category_importation_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_code',
            field=models.TextField(max_length=255, null=True, verbose_name='Id do Atleta'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.TextField(max_length=255, null=True, verbose_name='Clube'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome do Atleta'),
        ),
    ]
