# Generated by Django 4.1.1 on 2022-12-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_athlete_athlete_code_alter_athlete_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
