# Generated by Django 4.1.1 on 2022-12-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athlete_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_1', to='api.athlete', verbose_name='Atleta 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='athlete_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_2', to='api.athlete', verbose_name='Atleta 2'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.TextField(default=None, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
