# Generated by Django 4.1.1 on 2022-12-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_team_athlete_1_team_athlete_2_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField()),
                ('scorePoints', models.IntegerField()),
                ('athlete1MemberID', models.TextField(max_length=50)),
                ('athlete1Name', models.TextField(max_length=255)),
                ('athlete1Age', models.IntegerField()),
                ('athlete1Club', models.TextField(max_length=255)),
                ('athlete2MemberID', models.TextField(max_length=50)),
                ('athlete2Name', models.TextField(max_length=255)),
                ('athlete2Age', models.IntegerField()),
                ('athlete2Club', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='end',
            field=models.DateField(null=True, verbose_name='Data de Fim do Campeonato'),
        ),
        migrations.AddField(
            model_name='championship',
            name='name',
            field=models.TextField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
