# Generated by Django 4.1.1 on 2022-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rankingclassification_championship_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Club',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1MemberID',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Club',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2MemberID',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Name',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='category',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='classification',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='scorePoints',
            field=models.IntegerField(null=True),
        ),
    ]
