# Generated by Django 4.1.1 on 2022-12-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_rankingclassification_athlete1age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Club',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1MemberID',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Club',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2MemberID',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='category',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='classification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='scorePoints',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
