# Generated by Django 4.1.1 on 2022-12-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rankingclassification_athlete1club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete1Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='athlete2Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
