# Generated by Django 4.1.1 on 2022-12-05 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_alter_rankingclassification_athlete1age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipsheetimportation',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='championshipsheetimportation',
            name='file_name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='championshipsheetimportation',
            name='importation_date_time',
            field=models.DateField(null=True, verbose_name='Data de Importação'),
        ),
        migrations.AddField(
            model_name='classificationscore',
            name='classification',
            field=models.IntegerField(null=True, verbose_name='Posição da classificação'),
        ),
        migrations.AddField(
            model_name='classificationscore',
            name='score',
            field=models.FloatField(null=True, verbose_name='Pontuação da Posição'),
        ),
        migrations.AddField(
            model_name='configurationmodelranking',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='configurationmodelranking',
            name='score_weeks_expiration',
            field=models.IntegerField(null=True, verbose_name='Semanas até a expiração'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='championship_sheet_importation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.championshipsheetimportation', verbose_name='Planilha'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Data de Fim do Campeonato'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='json_data',
            field=models.TextField(max_length=50000, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='team_position_category_stage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamchampionshipstagecategory',
            name='team_position_stage_category',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AlterField(
            model_name='team',
            name='athlete_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_1', to='api.athlete', verbose_name='Atleta 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
