# Generated by Django 4.1.1 on 2022-12-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_championshipsheetimportation_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingclassification',
            name='category_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rankingclassification',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingclassification',
            name='ranking_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
