# Generated by Django 4.1.1 on 2022-12-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_file_championship_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='championship_name',
            field=models.TextField(max_length=255, null=True, verbose_name='Nome campeonato'),
        ),
        migrations.AddField(
            model_name='rankingclassification',
            name='championship',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
