# Generated by Django 4.1.1 on 2022-12-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_file_championship_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationscore',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='classificationscore',
            name='championship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.championship'),
        ),
        migrations.AddField(
            model_name='classificationscore',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='classificationscore',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
