# Generated by Django 4.1.1 on 2022-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_end_championship_occurrence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='championship_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Campeonato [PREENCHER APENAS NOS CASOS DE ARQUIVO DE CAMPEONATO]'),
        ),
        migrations.AlterField(
            model_name='file',
            name='championship_name',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Nome campeonato  [PREENCHER APENAS NOS CASOS DE ARQUIVO DE CAMPEONATO]'),
        ),
    ]
