# Generated by Django 4.1.1 on 2022-12-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_file_championship_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationscore',
            options={'verbose_name': 'Resultados de Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='rankingclassification',
            options={'verbose_name': 'Classificação Ranking'},
        ),
        migrations.AddField(
            model_name='rankingclassification',
            name='team',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
