# Generated by Django 4.1.1 on 2022-12-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_classificationscore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingclassification',
            name='team_name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclassification',
            name='team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
