# Generated by Django 4.1.1 on 2022-12-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rankingclassification_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category', verbose_name='Categoria'),
        ),
    ]
